/* Generated by           cobc 3.2.0 */
/* Generated from         acceptshell.cob */
/* Generated at           Jul 25 2025 13:03:22 */
/* GnuCOBOL build date    Sep 09 2024 19:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g acceptshell.cob */

/* Program local variables for 'ACCEPTSHELL' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[100] __attribute__((aligned));	/* CMD-LINE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_2	= {4, (cob_u8_t *)&b_2, &a_3};	/* RETURN-CODE */
static cob_field f_17	= {100, b_17, &a_2};	/* CMD-LINE */

/* End of fields */

