/* Generated by           cobc 3.2.0 */
/* Generated from         acceptshell.cob */
/* Generated at           Jul 25 2025 13:03:22 */
/* GnuCOBOL build date    Sep 09 2024 19:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g acceptshell.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x1b,   9,   0, 0x0041, NULL};


/* Constants */
static const cob_field c_1	= {29, (cob_u8_ptr)"Enter a shell command to run:", &a_1};
static const cob_field c_2	= {35, (cob_u8_ptr)"Command executed with return code: ", &a_1};


#define cob_nop	if (!module) cob_nop

