#line 1 "acceptshell.cob"
IDENTIFICATION DIVISION.
PROGRAM-ID. ACCEPTSHELL.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 CMD-LINE PIC X(100).


PROCEDURE DIVISION.
MAIN-PARAGRAPH.
 DISPLAY "Enter a shell command to run:"
 ACCEPT CMD-LINE

 CALL "SYSTEM" USING CMD-LINE


 DISPLAY "Command executed with return code: " RETURN-CODE
 STOP RUN.
