/* Generated by           cobc 3.2.0 */
/* Generated from         hello-dot-div.cbl */
/* Generated at           Jul 25 2025 12:06:19 */
/* GnuCOBOL build date    Sep 09 2024 19:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g hello-dot-div.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {19, (cob_u8_ptr)"Hello, COBOL world!", &a_1};


#define cob_nop	if (!module) cob_nop

