/* Generated by           cobc 3.2.0 */
/* Generated from         runshell.cob */
/* Generated at           Jul 25 2025 12:55:53 */
/* GnuCOBOL build date    Sep 09 2024 19:57:37 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -g runshell.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"runshell.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 25 2025 12:55:53"
#define  COB_MODULE_DATE		20250725
#define  COB_MODULE_TIME		125553

/* Global variables */
#include "runshell.c.h"

/* Function prototypes */

static int		RUNSHELL ();
static int		RUNSHELL_ (const int);
static void		RUNSHELL_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (RUNSHELL ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'RUNSHELL' */

/* ENTRY 'RUNSHELL' */

static int
RUNSHELL ()
{
  return RUNSHELL_ (0);
}

static int
RUNSHELL_ (const int entry)
{
  /* Program local variables */
  #include "runshell.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 10        : Entry     RUNSHELL                : runshell.cob */
  l_2:;
#line 10 "runshell.cob"
  ENTRY_RUNSHELL:	cob_nop ();
#line 105 "runshell.c"

  /* Line: 10        : PERFORM            : runshell.cob */
#line 10 "runshell.cob"
  cob_nop ();
#line 110 "runshell.c"
  /* PERFORM MAIN-PARAGRAPH */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_6;
  goto l_5;
  l_6:
  frame_ptr--;

  /* Line: 11        : STOP RUN           : runshell.cob */
#line 11 "runshell.cob"
  cob_nop ();
#line 124 "runshell.c"
  cob_stop_run (b_2);

  /* Line: 13        : Paragraph MAIN-PARAGRAPH          : runshell.cob */
  l_5:;
#line 13 "runshell.cob"
  PARAGRAPH_MAIN__PARAGRAPH_l_5:	cob_nop ();
#line 131 "runshell.c"

  /* Line: 14        : DISPLAY            : runshell.cob */
#line 14 "runshell.cob"
  cob_nop ();
#line 136 "runshell.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 16        : MOVE               : runshell.cob */
#line 16 "runshell.cob"
  cob_nop ();
#line 142 "runshell.c"
  cob_move ((cob_field *)&c_2, &f_17);

  /* Line: 17        : CALL               : runshell.cob */
#line 17 "runshell.cob"
  cob_nop ();
#line 148 "runshell.c"
  cob_procedure_params[0] = &f_17;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cob_sys_system (b_17);

  /* Line: 20        : DISPLAY            : runshell.cob */
#line 20 "runshell.cob"
  cob_nop ();
#line 157 "runshell.c"
  cob_display (0, 1, 2, &c_3, &f_2);

  /* Line: 22        : DISPLAY            : runshell.cob */
#line 22 "runshell.cob"
  cob_nop ();
#line 163 "runshell.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 24        : MOVE               : runshell.cob */
#line 24 "runshell.cob"
  cob_nop ();
#line 169 "runshell.c"
  cob_move ((cob_field *)&c_5, &f_17);

  /* Line: 25        : CALL               : runshell.cob */
#line 25 "runshell.cob"
  cob_nop ();
#line 175 "runshell.c"
  cob_procedure_params[0] = &f_17;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cob_sys_system (b_17);

  /* Line: 28        : DISPLAY            : runshell.cob */
#line 28 "runshell.cob"
  cob_nop ();
#line 184 "runshell.c"
  cob_display (0, 1, 2, &c_3, &f_2);

  /* Line: 30        : STOP RUN           : runshell.cob */
#line 30 "runshell.cob"
  cob_nop ();
#line 190 "runshell.c"
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  RUNSHELL_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field CMD-Line */
#line 6 "runshell.cob"
  cob_nop ();
#line 247 "runshell.c"
  memset (b_17, (unsigned char)' ', 100);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'RUNSHELL' */

/* Initialize module structure for RUNSHELL */
static void RUNSHELL_module_init (cob_module *module)
{
  module->module_name = "RUNSHELL";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())RUNSHELL;
  module->module_cancel.funcptr = (void *(*)())RUNSHELL_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

